name: Delete workflow runs

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master

on:
  workflow_dispatch:
 # schedule:
  #  - cron: 0 16 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 0
