name: Start compiling

on:
  workflow_dispatch:
 # schedule:
  #  - cron: 00 16 * * *

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set time
      run: |
       sudo timedatectl set-timezone "$TZ"
       echo "DATE=$(date "+%Y-%m-%d %H:%M")" >> $GITHUB_ENV
    - name: Trigger build
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        event-type: Start at ${{ env.DATE }}
